FROM ruby:2.3.3
MAINTAINER engineering@phogolabs.com

# UTF-8 SYSTEM LOCALE
# https://oncletom.io/2015/docker-encoding/
ENV LANG C.UTF-8

RUN gem install bundler
RUN gem install nokogiri
RUN gem install rspec
RUN gem install capybara
RUN gem install webmock
RUN gem install rake
RUN gem install rack
RUN gem install sinatra
