---
resources:
- name: docker-image-ruby
  type: docker-image
  source:
    email: "{{docker-hub-email}}"
    username: "{{docker-hub-username}}"
    password: "{{docker-hub-password}}"
    repository: phogo/ruby

- name: dockerfile-ruby
  type: git
  source:
    uri: git@github.com:phogolabs/docker-images.git
    paths: ["ruby/*"]
    branch: master
    private_key: "{{git-private-key}}"

jobs:
- name: build-ruby-docker-image
  max_in_flight: 1
  plan:
    - get: dockerfile-ruby
      trigger: true
    - put: docker-image-ruby
      params: 
        build: dockerfile-ruby/ruby
        tag_as_latest: true
