---
groups:
  - name: docker-images
    jobs:
    - patch
    - minor
    - major
    - build
    - promote

jobs:
  - name: build
    serial_groups: [build-image]
    public: true
    serial: true
    plan:
      - get: docker-file
        trigger: true
      - put: docker-image-experimental
        params: {build: {{docker-file-path}}}

  - name: promote
    serial_groups: [version, build-image]
    public: true
    serial: true
    plan:
      - get: docker-image-experimental
        trigger: false
        params: {save: true}
        passed: [build]
      - get: version
        trigger: true
      - put: docker-image
        params:
         load: docker-image-experimental
         load_file: docker-image-experimental/image
         load_repository: {{docker-hub-image}}
         load_tag: experimental
         tag: version/number
         tag_as_latest: true

  - name: patch
    serial_groups: [version]
    public: true
    plan:
      - get: version
        trigger: false
        params: {bump: patch}
      - put: version
        params: {file: version/number}

  - name: minor
    serial_groups: [version]
    public: true
    plan:
      - get: version
        trigger: false
        params: {bump: minor}
      - put: version
        params: {file: version/number}

  - name: major
    serial_groups: [version]
    public: true
    plan:
      - get: version
        trigger: false
        params: {bump: minor}
      - put: version
        params: {file: version/number}

resources:
  - name: docker-file
    type: git
    source:
      uri: git@github.com:phogolabs/docker-images.git
      branch: master
      private_key: {{github-private-key}}

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:phogolabs/docker-images.git
      branch: version
      initial_version: 0.0.1
      git_user: {{github-bot-user}}
      private_key: {{github-private-key}}
      file: {{docker-image-version-file}}

  - name: docker-image
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-image}}

  - name: docker-image-experimental
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-image}}
      tag: experimental
