---
groups:
  - name: docker-images
    jobs:
    - build
    - minor
    - major

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - get: docker-file
        trigger: true
      - put: version
        params: {pre: rc}
      - put: docker-image
        params:
         build: {{docker-file-path}}
         tag_prefix: "v"
         tag: version/number

  - name: minor
    public: true
    plan:
      - get: version
        trigger: false
        params: {bump: minor}
      - put: version
        params: {file: version/number}

  - name: major
    public: true
    plan:
      - get: version
        trigger: false
        params: {bump: minor}
      - put: version
        params: {file: version/number}

resources:
  - name: docker-file
    type: git
    source:
      uri: git@github.com:phogolabs/docker-images.git
      branch: master
      private_key: {{github-private-key}}

  - name: version
    type: semver
    source:
      driver: git
      git_user: {{git-bot-user}}
      initial_version: 0.0.1
      uri: git@github.com:phogolabs/docker-images.git
      private_key: {{github-private-key}}
      branch: version
      file: {{docker-image-version-file}}

  - name: docker-image
    type: docker-image
    source:
      email: {{dockerhub-email}}
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}
      repository: {{dockerhub-image}}
